function feature_vector = get_color_feature(i_img, pixels)
descriptors = {...
    'rgbhistogram',...
    'opponenthistogram',...
    'huehistogram',...
    'nrghistogram',...
    'transformedcolorhistogram',...
    'colormoments',...
    'colormomentinvariants',...
    'sift',...
    'huesift',...
    'hsvsift',...
    'opponentsift',...
    'rgsift',...
    'csift',...
    'rgbsift'};

detectors = {'densesampling'};
feature_vector = [];
nyu_globals;
descriptor = descriptors([1, 2, 6]);
for i_desc = 1 : length(descriptor)
    visual_dir = fullfile(FEATURES_DIR, [descriptor{i_desc}, '_codebook']);
    codebookfile = fullfile(visual_dir, 'codebook.mat');
    codebook = load(codebookfile);
    num_codes = size(codebook.centers, 2);
    mask = zeros(480, 640);
    mask(pixels) = 1;
    [x, y] = find(mask == 1);
    seg = [x, y];
    data = load(fullfile(visual_dir, sprintf('%04d.mat', i_img)));
    [desc, ~] = getFeatMask(seg, data.desc, data.loc);    
    f_vector = vl_ikmeanshist(num_codes, desc);
    feature_vector = [feature_vector; f_vector]; %#ok<AGROW>
end